ansible_user: ec2-user
ansible_password: devOps321
MONGODB_HOST: mongodb-"{{ env }}".opsora.space
CATALOGUE_HOST: catalogue-"{{ env }}".opsora.space
REDIS_HOST: redis-"{{ env }}".opsora.space
USER_HOST: user-"{{ env }}".opsora.space
CART_HOST: cart-"{{ env }}".opsora.space
MYSQL_HOST: mysql-"{{ env }}".opsora.space
SHIPPING_HOST: shipping-"{{ env }}".opsora.space
RABBITMQ_HOST: rabbitmq-"{{ env }}".opsora.space
DISPATCH_HOST: dispatch-dev.opsora.space
