ansible_user: ec2-user
ansible_password: DevOps321
MONGODB_HOST: mongodb-Dev.opsora.space
CATALOGUE_HOST: catalogue-Dev.opsora.space
REDIS_HOST: redis-Dev.opsora.space
USER_HOST: user-Dev.opsora.space
CART_HOST: cart-Dev.opsora.space
MYSQL_HOST: mysql-Dev.opsora.space
SHIPPING_HOST: shipping-Dev.opsora.space
RABBITMQ_HOST: rabbitmq-Dev.opsora.space
PAYMENT_HOST: payment-Dev.opsora.space
DISPATCH_HOST: dispatch-Dev.opsora.space
