- name: Install python pip
  ansible.builtin.yum:
    name: python3-pip
    state: present

- name: Install boto libraries
  ansible.builtin.pip:
    name:
      - boto3
      - botocore
    executable: pip3.9

- name: Copying rabbitmq service
  ansible.builtin.copy:
    src: rabbitmq.repo
    dest: /etc/yum.repos.d/rabbitmq.repo

- name: Installing rabbitmq server
  ansible.builtin.dnf:
    name: rabbitmq-server
    state: present
    
- name: Start and enable rabbitmq server
  ansible.builtin.service:
    state: restarted
    enabled: yes
    name: rabbitmq-server

- name: Configuring rabbitmq user
  community.rabbitmq.rabbitmq_user:
    user: "{{ RABBITMQ_USER }}"
    password: "{{ RABBITMQ_PASSWORD }}"
    vhost: /
    configure_priv: ".*"
    read_priv: ".*"
    write_priv: ".*"
    state: present